
// src/app/goldsmith-portal/register/page.tsx
'use client';

import type { Goldsmith, NewGoldsmithInput } from '@/types/goldsmith';
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { CheckCircle, Briefcase, Loader2, ShieldCheck } from 'lucide-react'
import Link from 'next/link'
import { useToast } from '@/hooks/use-toast';
import { useRouter } from 'next/navigation';
import { useState, type FormEvent } from 'react';
import { saveGoldsmith } from '@/actions/goldsmith-actions';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { auth } from '@/lib/firebase/firebase'; // Import Firebase auth
import { createUserWithEmailAndPassword, type UserCredential, type AuthError } from 'firebase/auth';


export default function GoldsmithRegisterPage() {
  const { toast } = useToast();
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Form state
  const [workshopName, setWorkshopName] = useState('');
  const [contactPerson, setContactPerson] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');
  const [specialties, setSpecialties] = useState(''); // Single string for input
  const [portfolioLink, setPortfolioLink] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    setIsSubmitting(true);

    if (password !== confirmPassword) {
      toast({ title: 'Registration Error', description: 'Passwords do not match.', variant: 'destructive' });
      setIsSubmitting(false);
      return;
    }

    try {
      // Step 1: Create user with Firebase Authentication
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      const firebaseUser = userCredential.user;

      if (firebaseUser && firebaseUser.uid) {
        // Step 2: Prepare goldsmith data for MongoDB (excluding password)
        const newGoldsmithData: NewGoldsmithInput = {
          name: workshopName,
          contactPerson,
          email, // Email is used as a unique identifier in Firebase Auth
          phone,
          address,
          specialty: specialties.split(',').map(s => s.trim()).filter(s => s),
          portfolioLink,
          // We'll associate this profile with the Firebase UID
          // The 'id' will be generated by the saveGoldsmith action
          // and 'status' will be set to 'pending_verification' by default
          // No password field here, as Firebase handles auth
          firebaseUID: firebaseUser.uid, // Store Firebase UID
        };

        // Step 3: Save profile information to MongoDB via Server Action
        const result = await saveGoldsmith(newGoldsmithData);

        if (result.success && result.data) {
          toast({
            title: 'Registration Submitted',
            description: 'Your workshop details have been submitted for review. Redirecting to login...',
          });
          setTimeout(() => {
            router.push('/goldsmith-portal/login');
          }, 2000);
        } else {
          // If saving to MongoDB fails, we might want to consider deleting the Firebase user
          // or implementing a retry mechanism. For now, we'll show an error.
          console.error("Failed to save goldsmith profile to MongoDB:", result.error);
          toast({
            title: 'Profile Save Failed',
            description: result.error || 'Could not save your profile after account creation. Please contact support.',
            variant: 'destructive',
          });
        }
      } else {
        throw new Error("Firebase user creation did not return a user or UID.");
      }
    } catch (error) {
      const authError = error as AuthError;
      console.error("Registration failed:", authError.code, authError.message);
      let description = authError.message || 'An unexpected error occurred during registration.';
      
      switch (authError.code) {
        case 'auth/email-already-in-use':
          description = 'This email address is already registered. Please try logging in or use a different email.';
          break;
        case 'auth/weak-password':
          description = 'The password is too weak. Please choose a stronger password (at least 6 characters).';
          break;
        case 'auth/invalid-email':
          description = 'The email address is not valid. Please enter a correct email.';
          break;
        // Add other Firebase Auth error codes as needed
      }
      toast({
        title: 'Registration Failed',
        description: description,
        variant: 'destructive',
      });
    } finally {
        setIsSubmitting(false);
    }
  };

  const isFormDisabled = isLoading || isSubmitting;

  return (
    <div className="flex justify-center items-center min-h-[calc(100vh-10rem)] py-10 bg-gradient-to-br from-secondary/20 to-background">
      <Card className="w-full max-w-2xl shadow-xl border-primary/15 rounded-xl bg-card">
        <CardHeader className="text-center pt-6 pb-4">
          <Briefcase className="h-12 w-12 mx-auto text-primary mb-3" />
          <CardTitle className="text-3xl text-accent font-heading">Register Your Goldsmith Workshop</CardTitle>
          <CardDescription className="text-muted-foreground mt-1 text-sm font-poppins">Join our curated network of skilled artisans. Please fill in your details below.</CardDescription>
        </CardHeader>
        <CardContent className="px-6 pb-6 pt-4">
          <form className="space-y-3.5" onSubmit={handleSubmit}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-5 gap-y-3">
               <div className="space-y-1">
                <Label htmlFor="workshopName" className="text-foreground">Workshop Name</Label>
                <Input id="workshopName" placeholder="e.g., Aura & Gold Creations" required className="text-foreground" value={workshopName} onChange={(e) => setWorkshopName(e.target.value)} disabled={isFormDisabled}/>
              </div>
               <div className="space-y-1">
                <Label htmlFor="contactPerson" className="text-foreground">Contact Person</Label>
                <Input id="contactPerson" placeholder="Your Full Name" required className="text-foreground" value={contactPerson} onChange={(e) => setContactPerson(e.target.value)} disabled={isFormDisabled}/>
              </div>
            </div>

            {/* Email (No OTP) */}
            <div className="space-y-1">
                <Label htmlFor="email" className="text-foreground">Business Email Address</Label>
                <Input id="email" type="email" placeholder="contact@auragold.com" required className="text-foreground flex-grow" value={email} onChange={(e) => setEmail(e.target.value)} disabled={isFormDisabled}/>
            </div>

            {/* Phone (No OTP) */}
             <div className="space-y-1">
                <Label htmlFor="phone" className="text-foreground">Business Phone Number</Label>
                <Input id="phone" type="tel" placeholder="e.g., 9876543210" required className="text-foreground flex-grow" value={phone} onChange={(e) => setPhone(e.target.value)} disabled={isFormDisabled}/>
            </div>

            <div className="space-y-1">
              <Label htmlFor="address" className="text-foreground">Workshop Address</Label>
              <Textarea id="address" placeholder="Full address of your workshop or studio" required rows={2} className="text-foreground" value={address} onChange={(e) => setAddress(e.target.value)} disabled={isFormDisabled}/>
            </div>

             <div className="space-y-1">
              <Label htmlFor="specialties" className="text-foreground">Specialties & Techniques</Label>
              <Input id="specialties" placeholder="e.g., Custom Engagement Rings, Hand Engraving, Gemstone Setting" required className="text-foreground" value={specialties} onChange={(e) => setSpecialties(e.target.value)} disabled={isFormDisabled}/>
               <p className="text-xs text-muted-foreground pt-0.5">Separate multiple specialties with commas.</p>
            </div>

            <div className="space-y-1">
              <Label htmlFor="portfolioLink" className="text-foreground">Portfolio Link (Website, Instagram, etc.)</Label>
              <Input id="portfolioLink" type="url" placeholder="https://yourportfolio.com" className="text-foreground" value={portfolioLink} onChange={(e) => setPortfolioLink(e.target.value)} disabled={isFormDisabled}/>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-5 gap-y-3">
              <div className="space-y-1">
                <Label htmlFor="password" className="text-foreground">Create Password</Label>
                <Input id="password" type="password" required className="text-foreground" value={password} onChange={(e) => setPassword(e.target.value)} disabled={isFormDisabled}/>
              </div>
               <div className="space-y-1">
                <Label htmlFor="confirmPassword" className="text-foreground">Confirm Password</Label>
                <Input id="confirmPassword" type="password" required className="text-foreground" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} disabled={isFormDisabled}/>
              </div>
            </div>

            <Alert variant="default" className="mt-4 bg-primary/5 border-primary/20 text-xs">
                <ShieldCheck className="h-4 w-4 text-primary/70" />
                <AlertTitle className="text-primary/90 font-medium">Admin Verification Required</AlertTitle>
                <AlertDescription className="text-muted-foreground">
                    Your registration will be submitted for admin review. You will be notified upon approval.
                </AlertDescription>
            </Alert>

            <Button 
                type="submit" 
                size="lg" 
                className="w-full shadow-md hover:shadow-lg transition-shadow rounded-full text-base py-3 mt-2.5 bg-primary hover:bg-primary/90 text-primary-foreground" 
                disabled={isFormDisabled || isSubmitting}
            >
              {isSubmitting ? <Loader2 className="mr-2 h-5 w-5 animate-spin"/> : <CheckCircle className="mr-2 h-5 w-5"/>}
              {isSubmitting ? 'Submitting...' : 'Submit Registration'}
            </Button>
             <p className="text-center text-sm text-muted-foreground pt-3">
                Already a partner?{' '}
                <Link href="/goldsmith-portal/login" className="font-semibold text-primary hover:text-primary/80 underline underline-offset-2 transition-colors">
                  Login to your portal
                </Link>
              </p>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
